@api = http://localhost:2500/api/congregaciones

### GET ALL
GET {{api}}/

### CREATE
POST {{api}}/
Content-Type: application/json

{
    "name": "Maestros y Videntes De Amor",
    "active": 1
}

### GET BY ID
GET {{api}}/1

### UPDATE BY ID
PUT {{api}}/5
Content-Type: application/json

{
    "name": "Congregacion 4",
    "active": 1
}

### DELETE BY ID
DELETE {{api}}/3
