@api = http://localhost:5500/api/congregaciones

### GET ALL
GET {{api}}/

### CREATE
POST {{api}}/
Content-Type: application/json

{
    "name": "Sebastián Escobar",
    "active": 1
}

### GET BY ID
GET {{api}}/1

### UPDATE BY ID
PUT {{api}}/1
Content-Type: application/json

{
    "name": "Congregacion Divina",
    "active": 1
}

### DELETE BY ID
DELETE {{api}}/3