@api = http://18.191.241.194:5500/api/facturaciones
@apiserver = https://congregapp.sebasescobar.com/api/facturaciones
### GET ALL
GET {{apiserver}}/

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "contacto_id" : 1,
    "user_id" : 1,
    "card_id" : 1,
    "moneda_id" : 1,
    "valor" : 1000,
    "estado_id" : 1,
    "congregacion_id" : 1
}

### GET BY ID
GET {{api}}/1

### UPDATE BY ID
PUT {{api}}/1
Content-Type: application/json

{
    "contacto_id" : 1,
    "user_id" : 2,
    "card_id" : 1,
    "moneda_id" : 1,
    "valor" : 1000,
    "estado_id" : 1,
}

### DELETE BY ID
DELETE {{api}}/1