@api = http://localhost:5500/api/facturaciones

### GET ALL
GET {{api}}/

### CREATE
POST {{api}}/
Content-Type: application/json

{
    "contacto_id" : 1,
    "user_id" : 1,
    "card_id" : 1,
    "moneda_id" : 1,
    "valor" : 1000.00,
    "estado_id" : 1,
    "congregacion_id" : 1
}

### GET BY ID
GET {{api}}/1

### UPDATE BY ID
PUT {{api}}/1
Content-Type: application/json

{
    "name":"Sebastián González Escobarrr",
    "email":"admin@master.com",
    "password": "qaws12pj-22",
    "active":1,
    "rol_id":1,
    "congregacion_id":1
}

### DELETE BY ID
DELETE {{api}}/1