@api = http://18.191.241.194:5500/api/roles
@apiserver = https://congregapp.sebasescobar.com/api/roles
### GET ALL
GET {{apiserver}}/

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "Administrador",
    "congregacion_id":1
}

### GET BY ID
GET {{api}}/1

### UPDATE BY ID
PUT {{apiserver}}/7
Content-Type: application/json

{
    "name": "Administrador",
    "congregacion_id":2
}

### DELETE BY ID
DELETE {{api}}/1