@api = http://18.191.241.194:5500/api/roles
@apiserver = https://congregapp.sebasescobar.com/api/roles
### GET ALL
GET {{apiserver}}/

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "Administrador"
}

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "Supervisor"
}

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "Maestro"
}

### GET BY ID
GET {{apiserver}}/1

### UPDATE BY ID
PATCH {{apiserver}}/1
Content-Type: application/json

{
    "name": "Administrador"
}

### DELETE BY ID
DELETE {{apiserver}}/1