@api = http://18.191.241.194:5500/api/masters

@apiserver = https://congregapp.sebasescobar.com/api/masters
### GET ALL
GET {{apiserver}}/

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name":"Sebastián Gónzalez Escobar",
    "phone":"3148406835",
    "image":"url",
    "password": "qaws12pj-22",
    "active":1,
    "rol_id":1
}

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name":"Lida Escobar",
    "phone":"3105413233",
    "image":"url",
    "password": "qaws12pj-22",
    "active":1,
    "rol_id":2
}

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name":"Lizeth Catalina Gómez",
    "phone":"3148405919",
    "image":"url",
    "password": "qaws12pj-22",
    "active":1,
    "rol_id":3
}

### GET BY ID
GET {{apiserver}}/1

### UPDATE BY ID
PATCH {{apiserver}}/1
Content-Type: application/json

{
    "name":"Sebastián Gónzalez Escobar Update",
    "phone":"3148406835",
    "image":"linkimage",
    "active":1,
    "rol_id":1
}

### DELETE BY ID
DELETE {{apiserver}}/3


###
POST {{apiserver}}/login
Content-Type: application/json

{
    "phone":"3148406835",
    "password": "qaws12pj-22"
}

###
GET {{apiserver}}/get/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2MzA0MTczMjEsImV4cCI6MTYzMDUwMzcyMX0.dy1NVJW0gEHh1q-wJThed89gylO1Gr4RQcT5H8-FQvk

