@api = http://18.191.241.194:5500/api/contact/status

@apiserver = https://congregapp.sebasescobar.com/api/contact/status
### GET ALL
GET {{apiserver}}/

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "Nuevo",
    "plural_name": "Nuevos"
}

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "Pendiente",
    "plural_name": "Pendientes"
}

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "En Consulta",
    "plural_name": "Consultas"
}

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "No Responde",
    "plural_name": "No Responden"
}

### GET BY ID
GET {{apiserver}}/1

### UPDATE BY ID
PATCH {{apiserver}}/2
Content-Type: application/json

{
    "name": "Pendiente",
    "plural_name": "Pendientes",
}

### DELETE BY ID
DELETE {{apiserver}}/1