@api = http://18.191.241.194:5500/api/contact/status

@apiserver = https://congregapp.sebasescobar.com/api/contact/status
### GET ALL
GET {{apiserver}}/

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "Nuevo",
    "plural_name": "Nuevos"
}

### GET BY ID
GET {{apiserver}}/1

### UPDATE BY ID
PATCH {{apiserver}}/1
Content-Type: application/json

{
    "name": "Nuevo UPDATE"
}

### DELETE BY ID
DELETE {{apiserver}}/1