@api = http://18.191.241.194:5500/api/estadoscontacto

@apiserver = https://congregapp.sebasescobar.com/api/estadoscontacto
### GET ALL
GET {{api}}/

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "Nuevo",
    "plural_name": "Nuevos",
    "congregacion_id": 1
}

### GET BY ID
GET {{api}}/1

### UPDATE BY ID
PUT {{api}}/1
Content-Type: application/json

{
    "name": "Nuevos"
}

### DELETE BY ID
DELETE {{api}}/1