@api = http://18.191.241.194:5500/api/contactos

### GET ALL
GET {{api}}/

### CREATE
POST {{api}}/
Content-Type: application/json

{
    "from": "Pruebas22",
    "name": "Ramiro22",
    "phone": "573148406835",
    "country": "COL",
    "estadocontacto_id": 1,
    "user_id": 1,
    "congregacion_id": 1
}

### GET BY ID
GET {{api}}/2

### UPDATE BY ID
PUT {{api}}/1
Content-Type: application/json

{
    "from": "Pruebas",
    "name": "Josefito González Bermudez",
    "phone": "573148406835",
    "country": "COL",
    "estadocontacto_id": 1,
    "user_id": 1,
    "congregacion_id": 1
}

### DELETE BY ID
DELETE {{api}}/1