@api = http://18.191.241.194:5500/api/currencies

@apiserver = https://congregapp.sebasescobar.com/api/currencies
### GET ALL
GET {{apiserver}}/

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "USD"
}

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "COP"
}

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "EUR"
}

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "name": "HNL"
}

### GET BY ID
GET {{apiserver}}/1

### UPDATE BY ID
PATCH {{apiserver}}/5
Content-Type: application/json

{
    "name": "EUR ( Euro )"
}

### DELETE BY ID
DELETE {{apiserver}}/1