@api = http://18.191.241.194:5500/api/monedas

@apiserver = https://congregapp.sebasescobar.com/api/monedas
### GET ALL
GET {{api}}/

### CREATE
POST {{api}}/
Content-Type: application/json

{
    "name": "USD",
    "congregacion_id": 1
}

### GET BY ID
GET {{api}}/1

### UPDATE BY ID
PUT {{api}}/1
Content-Type: application/json

{
    "name": "COP",
}

### DELETE BY ID
DELETE {{api}}/1