@api = http://localhost:2500/api/cards
@apiserver = https://congregapp.sebasescobar.com/api/cards

### GET ALL
GET {{apiserver}}/

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "active":1,
    "values": ["Sebastián González Escobar","1053855581", "Colombia", "Manizales", "170001"],
    "cardtype_id":1
}

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "active":1,
    "values": ["Lizeth Catalina Gómez Moreno","1018502364", "Colombia", "Manizales", "170001"],
    "cardtype_id":1
}

### CREATE
POST {{apiserver}}/
Content-Type: application/json

{
    "active":1,
    "values": ["Sebastián González Escobar","1053855581", "Manizales", "170001"],
    "cardtype_id":2
}

### GET BY ID
GET {{apiserver}}/2

### UPDATE BY ID
PATCH {{apiserver}}/1
Content-Type: application/json

{
    "active":1,
    "values": ["Sebastián González Escobar PATCHED","1053855581", "Colombia", "Manizales", "170001"],
    "cardtype_id":1
}
### DELETE BY ID
DELETE {{apiserver}}/1