@api = http://localhost:2500/api/cards

### GET ALL
GET {{api}}/

### CREATE
POST {{api}}/
Content-Type: application/json

{
    "active":1,
    "values": ["BC.1020","1053855581"],
    "typecard_id":1,
    "congregacion_id":1
}

### GET BY ID
GET {{api}}/2

### UPDATE BY ID
PUT {{api}}/1
Content-Type: application/json

{
    "active":0,
    "values": ["WC.1020","1053855581"],
    "typecard_id":1,
    "congregacion_id":1
}
### DELETE BY ID
DELETE {{api}}/1